In [8]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

In [9]:
dfSales = pd.read_csv("items_sales_data.csv", sep=';')
dfSalesGlobalQuantity = pd.read_csv("items_sales_data.csv", sep=';')
dfSales = dfSales.drop(columns=['GlobalQuantity'])
dfSalesGlobalQuantity = dfSalesGlobalQuantity.drop(columns=['UnitPrice', 'LineAmount', 'LastQuantity', 'DocumentDate'])
dfSales

,ItemNo,Nom,UnitPrice,LineAmount,LastQuantity,DocumentDate
0,1896-S,Bureau ATHÈNES,1005.8,1005.8,1,30/03/2026
1,1900-S,"Chaise dactylo PARIS, noire",193.7,1937.0,10,03/06/2026
2,1906-S,Socle mobile ATHÈNES,435.8,5229.6,12,03/06/2026
3,1908-S,"Chaise pivotante LONDRES, bleue",191.0,1719.0,9,03/06/2026
4,1920-S,Table de conférence ANVERS,651.1,5208.8,4,31/01/2026
5,1925-W,Offre groupée conférence 1-6,189.8,2087.8,11,03/06/2026
6,1928-S,Lampe AMSTERDAM,55.2,386.4,5,01/01/2026
7,1929-W,Offre groupée conférence 1-8,235.0,1175.0,5,03/06/2026
8,1936-S,"Chaise dactylo BERLIN, jaune",193.7,1937.0,23,31/01/2026
9,1953-W,Section invité 1,126.4,2148.8,17,03/06/2026
10,1960-S,"Chaise dactylo ROME, verte",193.7,581.1,3,03/06/2026
11,1964-S,"Chaise dactylo TOKYO, bleue",193.7,1937.0,10,03/06/2026
12,1965-W,Offre groupée conférence 2-8,235.0,1880.0,8,03/06/2026
13,1968-S,"Chaise pivotante MEXIQUE, noire",191.0,1910.0,5,31/03/2026
14,1969-W,Package conférence 1,343.5,5152.5,15,03/06/2026
15,1972-S,"Chaise pivotante MUNICH, jaune",191.0,573.0,3,03/06/2026
16,1980-S,"Chaise pivotante MOSCOU, rouge",191.0,2292.0,12,03/06/2026
17,1988-S,"Chaise dactylo SÉOUL, rouge",193.7,1355.9,7,03/06/2026
18,1996-S,"Tableau ATLANTA, socle",1404.3,16851.6,5,01/01/2026
19,2000-S,"Chaise pivotante SYDNEY, verte",191.0,955.0,2,01/01/2026
20,CC-1000,Crédit carbone 3 MTCO2e,240.0,480.0,2,03/06/2026
21,F-100,Pompe à distance,100.0,400.0,4,03/06/2026
22,F-101,Tasses à café en papier,2400.0,45600.0,19,03/06/2026
23,GRH-1000,Precision Grind Home,199.0,3582.0,18,03/06/2026
24,GRH-1001,Smart Grind Home,299.0,4485.0,15,03/06/2026
25,GTE-1000,"Grains torréfiés entiers, Colombie",15.0,300.0,2,04/06/2026
26,GTE-1001,"Grains torréfiés entiers, Brésil",15.0,150.0,2,05/06/2026
27,GTE-1002,"Grains torréfiés entiers, Indonésie",15.0,210.0,14,06/06/2026
28,S-100,S-100 Semi-Automatic,2400.0,2400.0,1,07/06/2026
29,S-210,S-210 Semi-Automatic,2400.0,45600.0,19,03/06/2026
30,SER101,Frais d’équipement,10.0,160.0,16,03/06/2026
31,SER102,Réparer,100.0,1100.0,11,03/06/2026
32,SERVICE203,Frais de projet,100.0,900.0,9,03/06/2026
33,SP-SCM1004,AutoDrip,179.0,3222.0,18,03/06/2026
34,SP-SCM1006,AutoDripLite,149.0,447.0,3,03/06/2026
35,SP-SCM1008,Airpot Lite,349.0,3141.0,9,03/06/2026
36,SP-SCM1009,Airpot,399.0,4788.0,12,03/06/2026
37,SP-SCM1011,Airpot Duo,499.0,8483.0,17,03/06/2026
38,WDB-1000,"Whole Decaf Beans, Colombia",180.0,3240.0,18,03/06/2026
39,WDB-1001,"Whole Decaf Beans, Brazil",210.0,420.0,2,03/06/2026
40,WDB-1002,"Whole Decaf Beans, Indonesia",210.0,1470.0,7,03/06/2026
41,WDB-1003,"Whole Decaf Beans, Mexico",210.0,2940.0,14,03/06/2026
42,WDB-1004,"Whole Decaf Beans, Kenya",210.0,1680.0,8,03/06/2026
43,WDB-1005,"Whole Decaf Beans, Costa Rica",210.0,2100.0,10,03/06/2026
44,WDB-1006,"Whole Decaf Beans, Ethiopia",210.0,3360.0,16,03/06/2026
45,WDB-1007,"Whole Decaf Beans, Hawaii",210.0,3150.0,15,03/06/2026
46,WRB-1003,"Whole Roasted Beans, Mexico",180.0,720.0,4,03/06/2026
47,WRB-1004,"Whole Roasted Beans, Kenya",180.0,1080.0,6,03/06/2026
48,WRB-1005,"Whole Roasted Beans, COSTA RICA",180.0,1620.0,9,03/06/2026
49,WRB-1006,"Whole Roasted Beans, ETHIOPIA",180.0,1800.0,10,03/06/2026
50,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026

In [10]:
dfSalesGlobalQuantity

        ItemNo                                  Nom  GlobalQuantity
0       1896-S                       Bureau ATHÈNES               1
1       1900-S          Chaise dactylo PARIS, noire              10
2       1906-S                 Socle mobile ATHÈNES              12
3       1908-S      Chaise pivotante LONDRES, bleue               9
4       1920-S           Table de conférence ANVERS              26
5       1925-W         Offre groupée conférence 1-6              11
6       1928-S                      Lampe AMSTERDAM              12
7       1929-W         Offre groupée conférence 1-8               5
8       1936-S         Chaise dactylo BERLIN, jaune              33
9       1953-W                     Section invité 1              17
10      1960-S           Chaise dactylo ROME, verte               3
11      1964-S          Chaise dactylo TOKYO, bleue              10
12      1965-W         Offre groupée conférence 2-8               8
13      1968-S      Chaise pivotante MEXIQUE, noire              15
14      1969-W                 Package conférence 1              15
15      1972-S       Chaise pivotante MUNICH, jaune               3
16      1980-S       Chaise pivotante MOSCOU, rouge              12
17      1988-S          Chaise dactylo SÉOUL, rouge               7
18      1996-S               Tableau ATLANTA, socle              24
19      2000-S       Chaise pivotante SYDNEY, verte              10
20     CC-1000              Crédit carbone 3 MTCO2e               2
21       F-100                     Pompe à distance               4
22       F-101              Tasses à café en papier              19
23    GRH-1000                 Precision Grind Home              18
24    GRH-1001                     Smart Grind Home              15
25    GTE-1000   Grains torréfiés entiers, Colombie              52
26    GTE-1001     Grains torréfiés entiers, Brésil              32
27    GTE-1002  Grains torréfiés entiers, Indonésie              14
28       S-100                 S-100 Semi-Automatic               1
29       S-210                 S-210 Semi-Automatic              19
30      SER101                   Frais d’équipement              16
31      SER102                              Réparer              11
32  SERVICE203                      Frais de projet               9
33  SP-SCM1004                             AutoDrip              18
34  SP-SCM1006                         AutoDripLite               3
35  SP-SCM1008                          Airpot Lite               9
36  SP-SCM1009                               Airpot              12
37  SP-SCM1011                           Airpot Duo              17
38    WDB-1000          Whole Decaf Beans, Colombia              18
39    WDB-1001            Whole Decaf Beans, Brazil               2
40    WDB-1002         Whole Decaf Beans, Indonesia               7
41    WDB-1003            Whole Decaf Beans, Mexico              14
42    WDB-1004             Whole Decaf Beans, Kenya               8
43    WDB-1005        Whole Decaf Beans, Costa Rica              10
44    WDB-1006          Whole Decaf Beans, Ethiopia              16
45    WDB-1007            Whole Decaf Beans, Hawaii              15
46    WRB-1003          Whole Roasted Beans, Mexico               4
47    WRB-1004           Whole Roasted Beans, Kenya               6
48    WRB-1005      Whole Roasted Beans, COSTA RICA               9
49    WRB-1006        Whole Roasted Beans, ETHIOPIA              10
50    WRB-1007          Whole Roasted Beans, HAWAII              16

In [11]:
''' dupliquer les lignes de dfSales en respectant les points suivants (1000 lignes au total)
        - garder le unitPrice
        - changer la quantité pour chaque ligne dupliquée
        - recalculer la quantité globale pour chaque article
        - mettre des dates supérieures pur calculer le profit sur une horizon de min. 5 ans
        - recalculer le montant ligne pour chaque article (unitPrice * last quantity)

'''

def dupliquer_lignes(df):
    List = []
    for index, row in df.iterrows():
        for i in range(20):
            row_dict = row.to_dict()
            List.append(row_dict)
    return pd.DataFrame(List)

        
dfSalesCopy = dupliquer_lignes(dfSales)
dfSalesCopy

,ItemNo,Nom,UnitPrice,LineAmount,LastQuantity,DocumentDate
0,1896-S,Bureau ATHÈNES,1005.8,1005.8,1,30/03/2026
1,1896-S,Bureau ATHÈNES,1005.8,1005.8,1,30/03/2026
2,1896-S,Bureau ATHÈNES,1005.8,1005.8,1,30/03/2026
3,1896-S,Bureau ATHÈNES,1005.8,1005.8,1,30/03/2026
4,1896-S,Bureau ATHÈNES,1005.8,1005.8,1,30/03/2026
...,...,...,...,...,...,...
1015,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026
1016,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026
1017,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026
1018,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026
1019,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026

In [12]:
dfSalesCopy["LastQuantity"] = np.random.randint(1, 20, size=len(dfSalesCopy))
dfSalesCopy["LineAmount"] = round(dfSalesCopy["UnitPrice"] * dfSalesCopy["LastQuantity"])
# dfSalesCopy["GlobalQuantity"] = dfSalesCopy["GlobalQuantity"] + dfSalesCopy["LastQuantity"]
dfSalesCopy

,ItemNo,Nom,UnitPrice,LineAmount,LastQuantity,DocumentDate
0,1896-S,Bureau ATHÈNES,1005.8,8046.0,8,30/03/2026
1,1896-S,Bureau ATHÈNES,1005.8,4023.0,4,30/03/2026
2,1896-S,Bureau ATHÈNES,1005.8,7041.0,7,30/03/2026
3,1896-S,Bureau ATHÈNES,1005.8,15087.0,15,30/03/2026
4,1896-S,Bureau ATHÈNES,1005.8,18104.0,18,30/03/2026
...,...,...,...,...,...,...
1015,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026
1016,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,360.0,2,03/06/2026
1017,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1080.0,6,03/06/2026
1018,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1620.0,9,03/06/2026
1019,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1800.0,10,03/06/2026

In [13]:
dfSalesGlobalBenefit = (
    dfSalesCopy.groupby('ItemNo', as_index=False)['LastQuantity']
    .sum()
    .rename(columns={'LastQuantity': 'GlobalQuantity'})
)
dfSalesGlobalBenefit['UnitPrice'] = dfSales['UnitPrice']
dfSalesGlobalBenefit['GlobalLineAmount'] = round(dfSalesGlobalBenefit['GlobalQuantity'] * dfSales['UnitPrice'])
dfSalesGlobalBenefit

        ItemNo  GlobalQuantity  UnitPrice  GlobalLineAmount
0       1896-S             180     1005.8          181044.0
1       1900-S             177      193.7           34285.0
2       1906-S             174      435.8           75829.0
3       1908-S             172      191.0           32852.0
4       1920-S             205      651.1          133476.0
5       1925-W             229      189.8           43464.0
6       1928-S             213       55.2           11758.0
7       1929-W             256      235.0           60160.0
8       1936-S             170      193.7           32929.0
9       1953-W             213      126.4           26923.0
10      1960-S             197      193.7           38159.0
11      1964-S             180      193.7           34866.0
12      1965-W             217      235.0           50995.0
13      1968-S             200      191.0           38200.0
14      1969-W             194      343.5           66639.0
15      1972-S             155      191.0           29605.0
16      1980-S             231      191.0           44121.0
17      1988-S             205      193.7           39708.0
18      1996-S             160     1404.3          224688.0
19      2000-S             204      191.0           38964.0
20     CC-1000             186      240.0           44640.0
21       F-100             233      100.0           23300.0
22       F-101             200     2400.0          480000.0
23    GRH-1000             241      199.0           47959.0
24    GRH-1001             220      299.0           65780.0
25    GTE-1000             189       15.0            2835.0
26    GTE-1001             209       15.0            3135.0
27    GTE-1002             208       15.0            3120.0
28       S-100             201     2400.0          482400.0
29       S-210             210     2400.0          504000.0
30      SER101             132       10.0            1320.0
31      SER102             214      100.0           21400.0
32  SERVICE203             190      100.0           19000.0
33  SP-SCM1004             161      179.0           28819.0
34  SP-SCM1006             184      149.0           27416.0
35  SP-SCM1008             205      349.0           71545.0
36  SP-SCM1009             198      399.0           79002.0
37  SP-SCM1011             169      499.0           84331.0
38    WDB-1000             177      180.0           31860.0
39    WDB-1001             232      210.0           48720.0
40    WDB-1002             190      210.0           39900.0
41    WDB-1003             202      210.0           42420.0
42    WDB-1004             173      210.0           36330.0
43    WDB-1005             172      210.0           36120.0
44    WDB-1006             194      210.0           40740.0
45    WDB-1007             207      210.0           43470.0
46    WRB-1003             192      180.0           34560.0
47    WRB-1004             165      180.0           29700.0
48    WRB-1005             207      180.0           37260.0
49    WRB-1006             214      180.0           38520.0
50    WRB-1007             205      180.0           36900.0

In [14]:
dfSalesCopy

,ItemNo,Nom,UnitPrice,LineAmount,LastQuantity,DocumentDate
0,1896-S,Bureau ATHÈNES,1005.8,8046.0,8,30/03/2026
1,1896-S,Bureau ATHÈNES,1005.8,4023.0,4,30/03/2026
2,1896-S,Bureau ATHÈNES,1005.8,7041.0,7,30/03/2026
3,1896-S,Bureau ATHÈNES,1005.8,15087.0,15,30/03/2026
4,1896-S,Bureau ATHÈNES,1005.8,18104.0,18,30/03/2026
...,...,...,...,...,...,...
1015,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,03/06/2026
1016,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,360.0,2,03/06/2026
1017,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1080.0,6,03/06/2026
1018,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1620.0,9,03/06/2026
1019,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1800.0,10,03/06/2026

In [15]:
today = datetime.today()
ten_years_later = today + timedelta(days=365*10)

def random_future_date(start, end):
    delta = end - start
    random_days = random.randint(0, delta.days)
    return start + timedelta(days=random_days)

dfSalesCopy['DocumentDate'] = [
    random_future_date(today, ten_years_later) 
    for _ in range(len(dfSalesCopy))
]
dfSalesCopy.rename(columns={'LastQuantity': 'Quantity'}, inplace=True)
dfSalesCopy

,ItemNo,Nom,UnitPrice,LineAmount,Quantity,DocumentDate
0,1896-S,Bureau ATHÈNES,1005.8,8046.0,8,2027-10-10 12:10:59.432059
1,1896-S,Bureau ATHÈNES,1005.8,4023.0,4,2029-11-10 12:10:59.432059
2,1896-S,Bureau ATHÈNES,1005.8,7041.0,7,2033-03-08 12:10:59.432059
3,1896-S,Bureau ATHÈNES,1005.8,15087.0,15,2029-09-24 12:10:59.432059
4,1896-S,Bureau ATHÈNES,1005.8,18104.0,18,2026-12-22 12:10:59.432059
...,...,...,...,...,...,...
1015,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,2034-06-23 12:10:59.432059
1016,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,360.0,2,2032-04-27 12:10:59.432059
1017,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1080.0,6,2030-03-25 12:10:59.432059
1018,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1620.0,9,2034-01-25 12:10:59.432059
1019,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1800.0,10,2033-08-13 12:10:59.432059

In [16]:
dfSalesGlobalBenefit['DocumentDate'] = (
    dfSalesCopy.assign(DocumentDate=pd.to_datetime(dfSalesCopy['DocumentDate'], format='%d/%m/%Y'))
    .groupby('ItemNo')['DocumentDate']
    .max()
    .dt.strftime('%d/%m/%Y')
    .values
)
dfSalesCopy['DocumentDate'] = pd.to_datetime(dfSalesCopy['DocumentDate']).dt.strftime('%d/%m/%Y')

In [19]:
dfSalesCopy.to_csv("output/sales_data.csv", sep=';', encoding='utf-8-sig')
dfSalesCopy

,ItemNo,Nom,UnitPrice,LineAmount,Quantity,DocumentDate
0,1896-S,Bureau ATHÈNES,1005.8,8046.0,8,10/10/2027
1,1896-S,Bureau ATHÈNES,1005.8,4023.0,4,10/11/2029
2,1896-S,Bureau ATHÈNES,1005.8,7041.0,7,08/03/2033
3,1896-S,Bureau ATHÈNES,1005.8,15087.0,15,24/09/2029
4,1896-S,Bureau ATHÈNES,1005.8,18104.0,18,22/12/2026
...,...,...,...,...,...,...
1015,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,2880.0,16,23/06/2034
1016,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,360.0,2,27/04/2032
1017,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1080.0,6,25/03/2030
1018,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1620.0,9,25/01/2034
1019,WRB-1007,"Whole Roasted Beans, HAWAII",180.0,1800.0,10,13/08/2033

In [20]:
dfSalesGlobalBenefit.to_csv("output/sales_global_benefit.csv", sep=';', encoding='utf-8-sig')
dfSalesGlobalBenefit

        ItemNo  GlobalQuantity  UnitPrice  GlobalLineAmount DocumentDate
0       1896-S             180     1005.8          181044.0   23/10/2035
1       1900-S             177      193.7           34285.0   01/10/2035
2       1906-S             174      435.8           75829.0   10/07/2035
3       1908-S             172      191.0           32852.0   31/03/2036
4       1920-S             205      651.1          133476.0   16/08/2035
5       1925-W             229      189.8           43464.0   13/01/2036
6       1928-S             213       55.2           11758.0   12/01/2036
7       1929-W             256      235.0           60160.0   19/12/2035
8       1936-S             170      193.7           32929.0   23/12/2035
9       1953-W             213      126.4           26923.0   31/01/2036
10      1960-S             197      193.7           38159.0   23/02/2036
11      1964-S             180      193.7           34866.0   22/07/2035
12      1965-W             217      235.0           50995.0   07/01/2036
13      1968-S             200      191.0           38200.0   24/10/2035
14      1969-W             194      343.5           66639.0   09/06/2035
15      1972-S             155      191.0           29605.0   18/07/2035
16      1980-S             231      191.0           44121.0   01/12/2035
17      1988-S             205      193.7           39708.0   27/09/2035
18      1996-S             160     1404.3          224688.0   20/02/2036
19      2000-S             204      191.0           38964.0   02/07/2035
20     CC-1000             186      240.0           44640.0   01/09/2035
21       F-100             233      100.0           23300.0   10/01/2036
22       F-101             200     2400.0          480000.0   11/08/2035
23    GRH-1000             241      199.0           47959.0   02/03/2036
24    GRH-1001             220      299.0           65780.0   04/12/2035
25    GTE-1000             189       15.0            2835.0   02/02/2036
26    GTE-1001             209       15.0            3135.0   17/11/2035
27    GTE-1002             208       15.0            3120.0   09/05/2035
28       S-100             201     2400.0          482400.0   04/01/2036
29       S-210             210     2400.0          504000.0   29/08/2035
30      SER101             132       10.0            1320.0   20/02/2036
31      SER102             214      100.0           21400.0   12/11/2035
32  SERVICE203             190      100.0           19000.0   04/08/2035
33  SP-SCM1004             161      179.0           28819.0   24/02/2036
34  SP-SCM1006             184      149.0           27416.0   15/05/2035
35  SP-SCM1008             205      349.0           71545.0   29/12/2035
36  SP-SCM1009             198      399.0           79002.0   14/01/2036
37  SP-SCM1011             169      499.0           84331.0   11/12/2035
38    WDB-1000             177      180.0           31860.0   31/12/2035
39    WDB-1001             232      210.0           48720.0   04/12/2035
40    WDB-1002             190      210.0           39900.0   17/01/2035
41    WDB-1003             202      210.0           42420.0   26/01/2036
42    WDB-1004             173      210.0           36330.0   27/03/2036
43    WDB-1005             172      210.0           36120.0   19/01/2036
44    WDB-1006             194      210.0           40740.0   25/06/2035
45    WDB-1007             207      210.0           43470.0   21/02/2036
46    WRB-1003             192      180.0           34560.0   17/12/2035
47    WRB-1004             165      180.0           29700.0   14/10/2035
48    WRB-1005             207      180.0           37260.0   05/08/2035
49    WRB-1006             214      180.0           38520.0   25/11/2034
50    WRB-1007             205      180.0           36900.0   23/06/2034